# -*- coding: utf-8 -*-
"""Добро пожаловать в Colaboratory!

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

A = int(input())
B = int(input())

if A < B:
  for i in range(A,B+1):  
    print(i)
if A > B:
  for i in range(A,B-1,-1):
    print(i)

A = int(input())
B = int(input())

for i in range(A,B):
  i1 = i//1000
  i2 = i//100%10
  i3 = i//10%10
  i4 = i%10

  if (i1 == i4) and (i2 == i3):
    print (i)